// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GaoZiJia",
            "email": "boringmanman@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth-Service"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseAuth"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/role/:id/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Service"
                ],
                "summary": "获取角色详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "some id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseGetRole"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/roles/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Service"
                ],
                "summary": "获取角色列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseRoles"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/routes/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin-Service"
                ],
                "summary": "获取路由",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseRoute"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/token/": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth-Service"
                ],
                "summary": "刷新token",
                "parameters": [
                    {
                        "description": "参数无注释",
                        "name": "token_refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseAuth"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Service"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseUsers"
                        }
                    },
                    "401": {
                        "description": "header need Authorization data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "no api permission or no obj permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ResponseAuth": {
            "type": "object",
            "required": [
                "expires",
                "expires_refresh",
                "token",
                "token_refresh"
            ],
            "properties": {
                "expires": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "integer"
                },
                "expires_refresh": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "integer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "string"
                },
                "token_refresh": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.ResponseGetRole": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "create_user": {
                    "description": "创建用户",
                    "type": "string"
                },
                "father_id": {
                    "description": "父角色ID",
                    "type": "integer"
                },
                "father_name": {
                    "description": "父角色名",
                    "type": "string"
                },
                "id": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "integer"
                },
                "name": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "update_user": {
                    "description": "更新用户",
                    "type": "string"
                }
            }
        },
        "api.ResponseRoles": {
            "type": "object",
            "properties": {
                "data_list": {
                    "description": "uint32 page = 1;\nuint32 page_size = 2;\nuint32 total = 3;",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RoleItem"
                    }
                }
            }
        },
        "api.ResponseRoute": {
            "type": "object",
            "properties": {
                "item_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RouteItem"
                    }
                }
            }
        },
        "api.ResponseUsers": {
            "type": "object",
            "properties": {
                "data_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.User"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.RoleItem": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "create_user": {
                    "description": "创建用户",
                    "type": "string"
                },
                "father_id": {
                    "description": "父角色ID",
                    "type": "integer"
                },
                "father_name": {
                    "description": "父角色名",
                    "type": "string"
                },
                "id": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "integer"
                },
                "name": {
                    "description": "@gotags: validate:\"required\"",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "update_user": {
                    "description": "更新用户",
                    "type": "string"
                }
            }
        },
        "api.RouteItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RouteItem"
                    }
                },
                "key": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/api.RouteMeta"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "api.RouteMeta": {
            "type": "object",
            "properties": {
                "auths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "icon": {
                    "type": "string"
                },
                "rank": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.User": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.bic-gin.cn",
	BasePath:         "/api/bic-gin",
	Schemes:          []string{},
	Title:            "bic-gin api文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
